import type { AccountCOA } from '../../types/erp'

export const STANDARD_FNB_COA: Omit<AccountCOA, 'id' | 'balance'>[] = [
  // 1-xxxx ASET (ASSETS)
  {
    code: '1-1001',
    name: 'Kas di Laci Kasir',
    type: 'asset_cash',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1002',
    name: 'Bank Operasional (BCA/Mandiri)',
    type: 'asset_bank',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1003',
    name: 'Penampungan QRIS & Payment Gateway',
    type: 'asset_bank',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1100',
    name: 'Piutang Usaha B2B (Roastery / Katering)',
    type: 'asset_receivable',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1201',
    name: 'Persediaan Bahan Baku (Green Beans, Susu, Sirup)',
    type: 'asset_inventory',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1202',
    name: 'Persediaan Barang Jadi (Roasted Beans, Retail)',
    type: 'asset_inventory',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1203',
    name: 'Persediaan Packaging & Kemasan',
    type: 'asset_inventory',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1204',
    name: 'Persediaan Barang Dalam Proses (WIP Roasting)',
    type: 'asset_inventory',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1500',
    name: 'Aset Tetap - Mesin Espresso, Grinder & Peralatan',
    type: 'asset_fixed',
    category: 'Aset',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '1-1501',
    name: 'Akumulasi Penyusutan Peralatan',
    type: 'asset_contra_depreciation',
    category: 'Aset',
    normalBalance: 'credit',
    isLocked: true,
  },

  // 2-xxxx KEWAJIBAN (LIABILITIES)
  {
    code: '2-1001',
    name: 'Hutang Usaha (Accounts Payable / Supplier)',
    type: 'liability_payable',
    category: 'Kewajiban',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '2-1002',
    name: 'Hutang Penerimaan Barang Belum Ditagih (Unbilled Goods)',
    type: 'liability_payable',
    category: 'Kewajiban',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '2-1100',
    name: 'Hutang Pajak Restoran (PB1 10%)',
    type: 'liability_tax',
    category: 'Kewajiban',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '2-1101',
    name: 'Hutang PPN (11% / 12%)',
    type: 'liability_tax',
    category: 'Kewajiban',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '2-1102',
    name: 'Hutang PPh 21 Karyawan',
    type: 'liability_tax',
    category: 'Kewajiban',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '2-1200',
    name: 'Titipan Service Charge Karyawan',
    type: 'liability_accrued',
    category: 'Kewajiban',
    normalBalance: 'credit',
    isLocked: true,
  },

  // 3-xxxx EKUITAS (EQUITY)
  {
    code: '3-1001',
    name: 'Modal Disetor Pemilik',
    type: 'equity_capital',
    category: 'Ekuitas',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '3-2001',
    name: 'Laba Ditahan (Retained Earnings)',
    type: 'equity_retained_earnings',
    category: 'Ekuitas',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '3-2002',
    name: 'Laba Tahun Berjalan (Current Earnings)',
    type: 'equity_current_earnings',
    category: 'Ekuitas',
    normalBalance: 'credit',
    isLocked: true,
  },

  // 4-xxxx PENDAPATAN (REVENUE)
  {
    code: '4-1001',
    name: 'Pendapatan Penjualan Bar (Minuman & Makanan)',
    type: 'revenue_sales',
    category: 'Pendapatan',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '4-1002',
    name: 'Pendapatan Penjualan Roastery B2B (Biji Kopi)',
    type: 'revenue_sales',
    category: 'Pendapatan',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '4-1003',
    name: 'Pendapatan Penjualan Ritel & Merchandise',
    type: 'revenue_sales',
    category: 'Pendapatan',
    normalBalance: 'credit',
    isLocked: true,
  },
  {
    code: '4-2001',
    name: 'Potongan Penjualan & Diskon Promo',
    type: 'revenue_contra_discount',
    category: 'Pendapatan',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '4-3001',
    name: 'Pendapatan Bunga Bank & Lain-Lain',
    type: 'revenue_other',
    category: 'Pendapatan',
    normalBalance: 'credit',
    isLocked: true,
  },

  // 5-xxxx HARGA POKOK PENJUALAN (COGS)
  {
    code: '5-1001',
    name: 'HPP - Pemakaian Bahan Minuman Bar',
    type: 'cogs_beverage',
    category: 'HPP',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '5-1002',
    name: 'HPP - Pemakaian Bahan Makanan Dapur',
    type: 'cogs_food',
    category: 'HPP',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '5-1003',
    name: 'HPP - Pemakaian Kemasan & Packaging',
    type: 'cogs_packaging',
    category: 'HPP',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '5-1004',
    name: 'HPP - Biji Kopi Sangrai Roastery B2B',
    type: 'cogs_roastery',
    category: 'HPP',
    normalBalance: 'debit',
    isLocked: true,
  },

  // 6-xxxx BEBAN OPERASIONAL (OPERATING EXPENSES)
  {
    code: '6-1001',
    name: 'Beban Gaji & Upah Barista/Kitchen',
    type: 'expense_payroll',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-2001',
    name: 'Beban Sewa Gedung & Tempat Outlet',
    type: 'expense_rent',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-2002',
    name: 'Beban Listrik, Air & Gas Operasional',
    type: 'expense_utility',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-2003',
    name: 'Beban Internet & Komunikasi',
    type: 'expense_utility',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-2004',
    name: 'Beban Kas Kecil & Pengeluaran Darurat (Petty Cash)',
    type: 'expense_utility',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-3001',
    name: 'Beban Kerusakan, Basi & Susut Bahan (Waste/Spillage)',
    type: 'expense_waste',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-3002',
    name: 'Beban Selisih Kas Laci (Cash Discrepancy)',
    type: 'expense_cash_discrepancy',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-3003',
    name: 'Beban Promosi, Marketing & Compliment Tamu (On The House)',
    type: 'expense_other',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-4001',
    name: 'Beban Penyusutan Mesin & Peralatan',
    type: 'expense_depreciation',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
  {
    code: '6-5001',
    name: 'Beban Administrasi Bank & MDR QRIS',
    type: 'expense_other',
    category: 'Beban',
    normalBalance: 'debit',
    isLocked: true,
  },
]
