import type {
  Organization,
  Outlet,
  User,
  InventoryItem,
  MenuItem,
  ModifierGroup,
  TableFloor,
  PurchaseBill,
  SalesInvoiceB2B,
  WorkOrderProduction,
  StockTransfer,
  FixedAsset,
  JournalEntry,
  Recipe,
  StockMovement,
  Order,
  Shift,
} from '../../types/erp'
import {
  createJournalForPosSale,
  createJournalForPurchaseBill,
  createJournalForSalesInvoiceB2B,
} from '../accounting/engine'

export const INITIAL_ORG: Organization = {
  id: 'org-resto',
  name: 'Nusantara Bistro & Cafe Group',
  legalName: 'PT Nusantara Boga Kuliner',
  taxId_NPWP: '02.456.789.1-014.000',
  phone: '+62 21-7234-8899',
  address: 'Jl. Senopati No. 42, Kebayoran Baru, Jakarta Selatan',
  subscriptionPlan: 'enterprise',
  modules: {
    pos_quick_service: true,
    pos_dine_in_tables: true,
    kitchen_routing_kds: true,
    inventory_basic: true,
    inventory_recipes_hpp: true,
    multi_warehouse_transfer: true,
    batch_production_roasting: false, // Optional roastery disabled by default for standard cafe/resto
    b2b_wholesale_invoicing: true,
    accurate_grade_accounting: true,
    fixed_assets: true,
    bank_reconciliation: true,
    live_excel_export: true,
    official_pdf_export: true,
  },
  createdAt: Date.now() - 120 * 86400000,
}

export const CENTRAL_HQ_OUTLET: Outlet = {
  id: 'all',
  orgId: 'org-resto',
  name: 'Kantor Pusat (Semua Cabang / Konsolidasi)',
  code: 'HQ-ALL',
  address: 'Graha Nusantara HQ, Jl. Jend. Sudirman Kav. 52, Jakarta',
  phone: '021-72348800',
  isCentralHub: true,
  tableCount: 0,
  isActive: true,
  receiptConfig: {
    storeName: 'NUSANTARA BISTRO GROUP',
    branchName: 'Kantor Pusat (Konsolidasi)',
    legalAddress: 'Graha Nusantara HQ, Jakarta',
    phone: '021-72348800',
    paperWidth: '80mm',
    showTax: true,
    showServiceCharge: true,
    showModifierDetails: true,
    showCashierName: true,
    customFooterMessage: 'Laporan Konsolidasi Grup Restoran Nusantara',
  },
}

export function getInventoryOutletStock(item: InventoryItem, outletId?: string): number {
  if (!outletId || outletId === 'all') {
    if (item.stockByOutlet) {
      return Object.values(item.stockByOutlet).reduce((s, v) => s + v, 0)
    }
    return item.currentStock
  }
  if (item.stockByOutlet && item.stockByOutlet[outletId] !== undefined) {
    return item.stockByOutlet[outletId]
  }
  return item.currentStock
}

export const INITIAL_OUTLETS: Outlet[] = [
  {
    id: 'out-senopati',
    orgId: 'org-resto',
    name: 'Cabang Senopati (Resto & Bar)',
    code: 'OUT-01',
    address: 'Jl. Senopati No. 42, Jakarta Selatan',
    phone: '021-72348899',
    isCentralHub: false,
    receiptConfig: {
      storeName: 'NUSANTARA BISTRO & CAFE',
      branchName: 'Cabang Senopati Jakarta',
      legalAddress: 'Jl. Senopati No. 42, Jakarta Selatan',
      phone: '021-72348899',
      instagram: '@nusantarabistro.id',
      wifiPassword: 'makansampaikenyang',
      paperWidth: '58mm',
      showTax: true,
      showServiceCharge: true,
      showModifierDetails: true,
      showCashierName: true,
      customFooterMessage: 'Terima kasih atas kunjungan Anda! Selamat menikmati hidangan.',
      qrCodeUrl: 'https://nusantarabistro.id/feedback',
    },
  },
  {
    id: 'out-dago',
    orgId: 'org-resto',
    name: 'Cabang Dago (Cafe & Eatery)',
    code: 'OUT-02',
    address: 'Jl. Ir. H. Juanda No. 120, Dago, Bandung',
    phone: '022-2508811',
    isCentralHub: false,
    receiptConfig: {
      storeName: 'NUSANTARA BISTRO DAGO',
      branchName: 'Cabang Dago Bandung',
      legalAddress: 'Jl. Ir. H. Juanda No. 120, Bandung',
      phone: '022-2508811',
      instagram: '@nusantarabistro.dago',
      wifiPassword: 'kopidankuliner',
      paperWidth: '80mm',
      showTax: true,
      showServiceCharge: true,
      showModifierDetails: true,
      showCashierName: true,
      customFooterMessage: 'Cita Rasa Nusantara dalam Suasana Hangat.',
    },
  },
]

export const INITIAL_USERS: User[] = [
  { id: 'usr-1', orgId: 'org-resto', name: 'Pemilik Usaha', pin: '1234', role: 'owner', active: true },
  { id: 'usr-2', orgId: 'org-resto', outletId: 'out-senopati', name: 'Kasir Utama', pin: '1111', role: 'cashier', active: true },
  { id: 'usr-3', orgId: 'org-resto', outletId: 'out-senopati', name: 'Manager Operasional', pin: '2222', role: 'manager', active: true },
  { id: 'usr-4', orgId: 'org-resto', outletId: 'out-senopati', name: 'Koki Dapur', pin: '3333', role: 'kitchen', active: true },
  { id: 'usr-5', orgId: 'org-resto', outletId: 'out-senopati', name: 'Barista', pin: '4444', role: 'barista', active: true },
  { id: 'usr-6', orgId: 'org-resto', name: 'Finance & Akuntan', pin: '5555', role: 'accountant', active: true },
]

export const INITIAL_INVENTORY: InventoryItem[] = [
  // 1. DAGING & PROTEIN
  {
    id: 'inv-beef-wagyu',
    orgId: 'org-resto',
    code: 'PRT-WGY',
    name: 'Daging Sapi Wagyu Patty 150g',
    category: 'meat_poultry' as any,
    unit: 'kg',
    currentStock: 24.5,
    minStock: 8,
    unitCost: 110000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-beef-sirloin',
    orgId: 'org-resto',
    code: 'PRT-SRL',
    name: 'Daging Sapi Sirloin Aus Meltique',
    category: 'meat_poultry' as any,
    unit: 'kg',
    currentStock: 16.0,
    minStock: 5,
    unitCost: 185000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-chicken-fillet',
    orgId: 'org-resto',
    code: 'PRT-AYM',
    name: 'Daging Ayam Fillet Dada Segar',
    category: 'meat_poultry' as any,
    unit: 'kg',
    currentStock: 38.0,
    minStock: 10,
    unitCost: 48000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-chicken-wings',
    orgId: 'org-resto',
    code: 'PRT-WNG',
    name: 'Sayap Ayam Segar (Chicken Wings)',
    category: 'meat_poultry' as any,
    unit: 'kg',
    currentStock: 22.0,
    minStock: 8,
    unitCost: 42000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-fish-dori',
    orgId: 'org-resto',
    code: 'PRT-DOR',
    name: 'Ikan Dori Fillet Frozen Glazing 20%',
    category: 'meat_poultry' as any,
    unit: 'kg',
    currentStock: 18.0,
    minStock: 6,
    unitCost: 54000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-egg',
    orgId: 'org-resto',
    code: 'PRT-TLR',
    name: 'Telur Ayam Negeri Grade A',
    category: 'produce' as any,
    unit: 'butir',
    currentStock: 250,
    minStock: 60,
    unitCost: 2000,
    updatedAt: Date.now(),
  },

  // 2. BAHAN POKOK, KARBO & SEMBAKO
  {
    id: 'inv-rice',
    orgId: 'org-resto',
    code: 'SEM-BRS',
    name: 'Beras Pandan Wangi Premium',
    category: 'produce' as any,
    unit: 'kg',
    currentStock: 115,
    minStock: 25,
    unitCost: 16500,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-fries',
    orgId: 'org-resto',
    code: 'SEM-KNT',
    name: 'Kentang Beku Shoestring McCain',
    category: 'grocery_spices' as any,
    unit: 'kg',
    currentStock: 42.0,
    minStock: 15,
    unitCost: 32000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-pasta',
    orgId: 'org-resto',
    code: 'SEM-PST',
    name: 'Pasta Spaghetti San Remo 500g',
    category: 'grocery_spices' as any,
    unit: 'kg',
    currentStock: 26.0,
    minStock: 8,
    unitCost: 36000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-burger-bun',
    orgId: 'org-resto',
    code: 'SEM-BUN',
    name: 'Brioche Burger Bun Wijen Artisan',
    category: 'grocery_spices' as any,
    unit: 'pcs',
    currentStock: 54,
    minStock: 20,
    unitCost: 4500,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-cooking-oil',
    orgId: 'org-resto',
    code: 'SEM-MYK',
    name: 'Minyak Goreng Sawit Bimoli',
    category: 'grocery_spices' as any,
    unit: 'liter',
    currentStock: 36,
    minStock: 12,
    unitCost: 18000,
    updatedAt: Date.now(),
  },

  // 3. SAYURAN, BUMBU & SAUS
  {
    id: 'inv-shallots-garlic',
    orgId: 'org-resto',
    code: 'BMB-BWG',
    name: 'Bawang Merah & Putih Kupas Bersih',
    category: 'produce' as any,
    unit: 'kg',
    currentStock: 14.0,
    minStock: 4,
    unitCost: 35000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-chili',
    orgId: 'org-resto',
    code: 'BMB-CBE',
    name: 'Cabe Rawit Merah & Keriting Segar',
    category: 'produce' as any,
    unit: 'kg',
    currentStock: 8.5,
    minStock: 3,
    unitCost: 52000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-sauce-bbq',
    orgId: 'org-resto',
    code: 'BMB-BBQ',
    name: 'Saus BBQ & Blackpepper Khas Resto',
    category: 'grocery_spices' as any,
    unit: 'kg',
    currentStock: 12.0,
    minStock: 4,
    unitCost: 28000,
    updatedAt: Date.now(),
  },

  // 4. DAIRY & BAHAN MINUMAN BAR
  {
    id: 'inv-fresh-milk',
    orgId: 'org-resto',
    code: 'DRY-MLK',
    name: 'Greenfields Fresh Milk Pasteurized',
    category: 'dairy',
    unit: 'liter',
    currentStock: 52,
    minStock: 15,
    unitCost: 19000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-oat-milk',
    orgId: 'org-resto',
    code: 'DRY-OAT',
    name: 'Oatly Barista Edition Oat Milk',
    category: 'dairy',
    unit: 'liter',
    currentStock: 22,
    minStock: 6,
    unitCost: 44000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-cheese',
    orgId: 'org-resto',
    code: 'DRY-KJU',
    name: 'Keju Cheddar Slice & Parmesan Anchor',
    category: 'dairy',
    unit: 'kg',
    currentStock: 10.5,
    minStock: 3,
    unitCost: 85000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-cooking-cream',
    orgId: 'org-resto',
    code: 'DRY-CRM',
    name: 'Cooking Cream Anchor 1 Liter',
    category: 'dairy',
    unit: 'liter',
    currentStock: 14,
    minStock: 4,
    unitCost: 68000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-coffee-beans',
    orgId: 'org-resto',
    code: 'BAR-KOP',
    name: 'Biji Kopi House Blend Arabica-Robusta',
    category: 'beans_roasted',
    unit: 'kg',
    currentStock: 32.0,
    minStock: 10,
    unitCost: 145000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-matcha-powder',
    orgId: 'org-resto',
    code: 'BAR-MTC',
    name: 'Bubuk Matcha Premium Pure',
    category: 'beverage_raw' as any,
    unit: 'kg',
    currentStock: 4.5,
    minStock: 1.5,
    unitCost: 260000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-syrup-lychee',
    orgId: 'org-resto',
    code: 'BAR-LCI',
    name: 'Monin Syrup Lychee 700ml',
    category: 'syrup',
    unit: 'ml',
    currentStock: 2400,
    minStock: 700,
    unitCost: 210, // Rp 210 / ml
    updatedAt: Date.now(),
  },
  {
    id: 'inv-lychee-fruit',
    orgId: 'org-resto',
    code: 'BAR-BHL',
    name: 'Buah Leci Kaleng Tropical',
    category: 'beverage_raw' as any,
    unit: 'kaleng',
    currentStock: 16,
    minStock: 5,
    unitCost: 29000,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-tea-leaves',
    orgId: 'org-resto',
    code: 'BAR-TEH',
    name: 'Daun Teh Hitam Premium Artisan',
    category: 'beverage_raw' as any,
    unit: 'kg',
    currentStock: 6.0,
    minStock: 2,
    unitCost: 75000,
    updatedAt: Date.now(),
  },

  // 5. PACKAGING & TAKEAWAY
  {
    id: 'inv-box-takeaway',
    orgId: 'org-resto',
    code: 'PKG-BOX',
    name: 'Box Takeaway Kraft Eco Foodgrade',
    category: 'packaging',
    unit: 'pcs',
    currentStock: 380,
    minStock: 100,
    unitCost: 1400,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-cup-cold',
    orgId: 'org-resto',
    code: 'PKG-C16',
    name: 'Cold Plastic Cup 16oz + Straw',
    category: 'packaging',
    unit: 'pcs',
    currentStock: 600,
    minStock: 150,
    unitCost: 1200,
    updatedAt: Date.now(),
  },
  {
    id: 'inv-cup-hot',
    orgId: 'org-resto',
    code: 'PKG-C8',
    name: 'Hot Paper Cup 8oz + Lid',
    category: 'packaging',
    unit: 'pcs',
    currentStock: 320,
    minStock: 80,
    unitCost: 950,
    updatedAt: Date.now(),
  },
].map((item: InventoryItem) => {
  if (item.stockByOutlet) return item
  const senopatiStock = item.currentStock
  const dagoStock = Math.round(item.currentStock * 0.65 * 10) / 10
  const hqStock = Math.round(item.currentStock * 1.5 * 10) / 10
  return {
    ...item,
    stockByOutlet: {
      'out-senopati': senopatiStock,
      'out-dago': dagoStock,
      'hq': hqStock,
    },
    currentStock: Math.round((senopatiStock + dagoStock + hqStock) * 10) / 10,
  }
})

export const INITIAL_MODIFIER_GROUPS: ModifierGroup[] = [
  {
    id: 'mod-spiciness',
    name: 'Tingkat Kepedasan',
    required: false,
    maxSelection: 1,
    options: [
      { id: 'opt-spicy-mild', name: 'Sedang / Mild', priceAdd: 0 },
      { id: 'opt-spicy-hot', name: 'Pedas Mantap', priceAdd: 0 },
      { id: 'opt-spicy-extra', name: 'Ekstra Pedas Gila', priceAdd: 3000 },
    ],
  },
  {
    id: 'mod-egg-style',
    name: 'Pilihan Telur',
    required: false,
    maxSelection: 1,
    options: [
      { id: 'opt-egg-ceplok', name: 'Telur Ceplok (Mata Sapi)', priceAdd: 0 },
      { id: 'opt-egg-dadar', name: 'Telur Dadar Crispy', priceAdd: 0 },
      { id: 'opt-egg-extra', name: '+ Tambah 1 Telur Lagi', priceAdd: 5000, substituteInvItemId: 'inv-egg', invQtyUsed: 1 },
    ],
  },
  {
    id: 'mod-milk-choice',
    name: 'Pilihan Susu Minuman',
    required: false,
    maxSelection: 1,
    options: [
      { id: 'opt-milk-fresh', name: 'Fresh Milk Reguler', priceAdd: 0 },
      { id: 'opt-milk-oat', name: 'Ganti Oatly Oat Milk', priceAdd: 8000, substituteInvItemId: 'inv-oat-milk', invQtyUsed: 180 },
    ],
  },
  {
    id: 'mod-ice-sugar',
    name: 'Tingkat Manis & Es',
    required: false,
    maxSelection: 1,
    options: [
      { id: 'opt-norm', name: 'Normal Ice & Sugar', priceAdd: 0 },
      { id: 'opt-less', name: 'Less Sugar 50% & Less Ice', priceAdd: 0 },
      { id: 'opt-nosugar', name: 'No Sugar (Tanpa Gula)', priceAdd: 0 },
    ],
  },
]

export const INITIAL_MENU: MenuItem[] = [
  // MAKANAN UTAMA (HOT KITCHEN)
  {
    id: 'menu-nasgor',
    categoryId: 'cat-food',
    name: 'Nasi Goreng Kampung Spesial',
    price: 38000,
    active: true,
    modifierGroupIds: ['mod-spiciness', 'mod-egg-style'],
    isKitchenItem: true,
  },
  {
    id: 'menu-ayambakar',
    categoryId: 'cat-food',
    name: 'Ayam Bakar Sambal Matah',
    price: 45000,
    active: true,
    modifierGroupIds: ['mod-spiciness'],
    isKitchenItem: true,
  },
  {
    id: 'menu-burger',
    categoryId: 'cat-food',
    name: 'Wagyu Beef Burger & Truffle Fries',
    price: 65000,
    active: true,
    modifierGroupIds: ['mod-egg-style'],
    isKitchenItem: true,
  },
  {
    id: 'menu-carbonara',
    categoryId: 'cat-food',
    name: 'Spaghetti Carbonara Smoked Beef',
    price: 52000,
    active: true,
    isKitchenItem: true,
  },
  {
    id: 'menu-sirloin',
    categoryId: 'cat-food',
    name: 'Australian Sirloin Steak 200g',
    price: 115000,
    active: true,
    isKitchenItem: true,
  },
  {
    id: 'menu-dori',
    categoryId: 'cat-food',
    name: 'Dori Crispy Sambal Dabu-Dabu',
    price: 42000,
    active: true,
    modifierGroupIds: ['mod-spiciness'],
    isKitchenItem: true,
  },

  // SNACK & APPETIZER (KITCHEN)
  {
    id: 'menu-fries',
    categoryId: 'cat-snack',
    name: 'Truffle Parmesan French Fries',
    price: 28000,
    active: true,
    isKitchenItem: true,
  },
  {
    id: 'menu-wings',
    categoryId: 'cat-snack',
    name: 'Crispy Chicken Wings BBQ',
    price: 35000,
    active: true,
    modifierGroupIds: ['mod-spiciness'],
    isKitchenItem: true,
  },
  {
    id: 'menu-tahu',
    categoryId: 'cat-snack',
    name: 'Tahu Cabe Garam Crispy',
    price: 22000,
    active: true,
    isKitchenItem: true,
  },

  // KOPI & ESPRESSO (BAR)
  {
    id: 'menu-latte',
    categoryId: 'cat-coffee',
    name: 'Iced Caffe Latte',
    price: 32000,
    active: true,
    modifierGroupIds: ['mod-milk-choice', 'mod-ice-sugar'],
    isKitchenItem: false,
  },
  {
    id: 'menu-americano',
    categoryId: 'cat-coffee',
    name: 'Iced Americano',
    price: 25000,
    active: true,
    modifierGroupIds: ['mod-ice-sugar'],
    isKitchenItem: false,
  },
  {
    id: 'menu-caramel-macchiato',
    categoryId: 'cat-coffee',
    name: 'Caramel Macchiato',
    price: 38000,
    active: true,
    modifierGroupIds: ['mod-milk-choice'],
    isKitchenItem: false,
  },

  // NON-COFFEE & MOCKTAIL (BAR)
  {
    id: 'menu-matcha',
    categoryId: 'cat-beverage',
    name: 'Matcha Latte Premium',
    price: 35000,
    active: true,
    modifierGroupIds: ['mod-milk-choice', 'mod-ice-sugar'],
    isKitchenItem: false,
  },
  {
    id: 'menu-lychee-tea',
    categoryId: 'cat-beverage',
    name: 'Lychee Iced Tea',
    price: 28000,
    active: true,
    modifierGroupIds: ['mod-ice-sugar'],
    isKitchenItem: false,
  },
  {
    id: 'menu-mocktail-sunset',
    categoryId: 'cat-beverage',
    name: 'Tropical Sunset Mocktail',
    price: 32000,
    active: true,
    isKitchenItem: false,
  },

  // DESSERT & PASTRY
  {
    id: 'menu-croissant',
    categoryId: 'cat-dessert',
    name: 'Almond Butter Croissant',
    price: 26000,
    active: true,
    isKitchenItem: true,
  },
  {
    id: 'menu-cheesecake',
    categoryId: 'cat-dessert',
    name: 'Lotus Biscoff Cheesecake',
    price: 38000,
    active: true,
    isKitchenItem: true,
  },
]

export const INITIAL_RECIPES: Recipe[] = [
  // 1. Nasi Goreng Spesial (HPP Bahan: Rp 11.200 | Jual: Rp 38.000 | Food Cost: 29.5%)
  {
    id: 'rec-nasgor',
    menuItemId: 'menu-nasgor',
    ingredients: [
      { invItemId: 'inv-rice', invItemName: 'Beras Pandan Wangi', qty: 0.15, unit: 'kg' }, // Rp 2.475
      { invItemId: 'inv-egg', invItemName: 'Telur Ayam Negeri', qty: 1, unit: 'butir' }, // Rp 2.000
      { invItemId: 'inv-chicken-fillet', invItemName: 'Daging Ayam Fillet', qty: 0.08, unit: 'kg' }, // Rp 3.840
      { invItemId: 'inv-shallots-garlic', invItemName: 'Bawang Merah & Putih', qty: 0.03, unit: 'kg' }, // Rp 1.050
      { invItemId: 'inv-cooking-oil', invItemName: 'Minyak Goreng', qty: 0.03, unit: 'liter' }, // Rp 540
      { invItemId: 'inv-box-takeaway', invItemName: 'Box & Cutlery', qty: 1, unit: 'pcs' }, // Rp 1.400
    ],
    laborCostStd: 2500,
    overheadCostStd: 1500,
    notes: 'Porsi 1 piring lengkap acar dan kerupuk',
  },

  // 2. Ayam Bakar Sambal Matah (HPP Bahan: Rp 15.600 | Jual: Rp 45.000 | Food Cost: 34.6%)
  {
    id: 'rec-ayambakar',
    menuItemId: 'menu-ayambakar',
    ingredients: [
      { invItemId: 'inv-chicken-fillet', invItemName: 'Daging Ayam Fillet', qty: 0.20, unit: 'kg' }, // Rp 9.600
      { invItemId: 'inv-rice', invItemName: 'Beras Pandan Wangi', qty: 0.15, unit: 'kg' }, // Rp 2.475
      { invItemId: 'inv-chili', invItemName: 'Cabe Rawit & Sambal', qty: 0.04, unit: 'kg' }, // Rp 2.080
      { invItemId: 'inv-cooking-oil', invItemName: 'Minyak Kelapa Matah', qty: 0.02, unit: 'liter' }, // Rp 360
      { invItemId: 'inv-box-takeaway', invItemName: 'Kemasan', qty: 1, unit: 'pcs' }, // Rp 1.400
    ],
    laborCostStd: 3000,
    overheadCostStd: 1800,
    notes: 'Ayam 200g ungkep bakar sambal matah bali',
  },

  // 3. Wagyu Beef Burger (HPP Bahan: Rp 23.400 | Jual: Rp 65.000 | Food Cost: 36.0%)
  {
    id: 'rec-burger',
    menuItemId: 'menu-burger',
    ingredients: [
      { invItemId: 'inv-beef-wagyu', invItemName: 'Wagyu Beef Patty', qty: 0.15, unit: 'kg' }, // Rp 16.500
      { invItemId: 'inv-burger-bun', invItemName: 'Brioche Burger Bun', qty: 1, unit: 'pcs' }, // Rp 4.500
      { invItemId: 'inv-cheese', invItemName: 'Keju Cheddar Slice', qty: 0.03, unit: 'kg' }, // Rp 2.550
      { invItemId: 'inv-fries', invItemName: 'Kentang Goreng', qty: 0.08, unit: 'kg' }, // Rp 2.560
      { invItemId: 'inv-box-takeaway', invItemName: 'Burger Box Eco', qty: 1, unit: 'pcs' }, // Rp 1.400
    ],
    laborCostStd: 3500,
    overheadCostStd: 2000,
    notes: 'Wagyu patty 150g medium well dengan kentang',
  },

  // 4. Spaghetti Carbonara (HPP Bahan: Rp 16.800 | Jual: Rp 52.000 | Food Cost: 32.3%)
  {
    id: 'rec-carbonara',
    menuItemId: 'menu-carbonara',
    ingredients: [
      { invItemId: 'inv-pasta', invItemName: 'Spaghetti San Remo', qty: 0.12, unit: 'kg' }, // Rp 4.320
      { invItemId: 'inv-cooking-cream', invItemName: 'Cooking Cream Anchor', qty: 0.10, unit: 'liter' }, // Rp 6.800
      { invItemId: 'inv-egg', invItemName: 'Kuning Telur', qty: 1, unit: 'butir' }, // Rp 2.000
      { invItemId: 'inv-cheese', invItemName: 'Keju Parmesan', qty: 0.03, unit: 'kg' }, // Rp 2.550
      { invItemId: 'inv-box-takeaway', invItemName: 'Pasta Bowl', qty: 1, unit: 'pcs' }, // Rp 1.400
    ],
    laborCostStd: 3000,
    overheadCostStd: 1800,
    notes: 'Krim kental Italia dengan parmesan',
  },

  // 5. Truffle Parmesan Fries (HPP Bahan: Rp 8.800 | Jual: Rp 28.000 | Food Cost: 31.4%)
  {
    id: 'rec-fries',
    menuItemId: 'menu-fries',
    ingredients: [
      { invItemId: 'inv-fries', invItemName: 'Kentang Beku Shoestring', qty: 0.20, unit: 'kg' }, // Rp 6.400
      { invItemId: 'inv-cooking-oil', invItemName: 'Minyak Goreng', qty: 0.04, unit: 'liter' }, // Rp 720
      { invItemId: 'inv-cheese', invItemName: 'Keju Parmesan Tabur', qty: 0.015, unit: 'kg' }, // Rp 1.275
      { invItemId: 'inv-box-takeaway', invItemName: 'Snack Cone/Box', qty: 1, unit: 'pcs' }, // Rp 1.400
    ],
    laborCostStd: 1500,
    overheadCostStd: 1000,
    notes: 'Porsi 200 gram kentang renyah',
  },

  // 6. Iced Caffe Latte (HPP Bahan: Rp 6.800 | Jual: Rp 32.000 | Beverage Cost: 21.2%)
  {
    id: 'rec-latte',
    menuItemId: 'menu-latte',
    ingredients: [
      { invItemId: 'inv-coffee-beans', invItemName: 'House Blend Coffee Beans', qty: 0.018, unit: 'kg' }, // Rp 2.610
      { invItemId: 'inv-fresh-milk', invItemName: 'Greenfields Fresh Milk', qty: 0.18, unit: 'liter' }, // Rp 3.420
      { invItemId: 'inv-cup-cold', invItemName: 'Cold Cup 16oz + Straw', qty: 1, unit: 'pcs' }, // Rp 1.200
    ],
    laborCostStd: 1000,
    overheadCostStd: 600,
    notes: 'Double espresso 18g + susu 180ml + es batu',
  },

  // 7. Lychee Iced Tea (HPP Bahan: Rp 5.800 | Jual: Rp 28.000 | Beverage Cost: 20.7%)
  {
    id: 'rec-lychee-tea',
    menuItemId: 'menu-lychee-tea',
    ingredients: [
      { invItemId: 'inv-tea-leaves', invItemName: 'Daun Teh Hitam Seduh', qty: 0.01, unit: 'kg' }, // Rp 750
      { invItemId: 'inv-syrup-lychee', invItemName: 'Monin Lychee Syrup', qty: 25, unit: 'ml' }, // Rp 5.250
      { invItemId: 'inv-cup-cold', invItemName: 'Cold Cup 16oz', qty: 1, unit: 'pcs' }, // Rp 1.200
    ],
    laborCostStd: 800,
    overheadCostStd: 500,
    notes: 'Teh seduh segar dengan 2 buah leci',
  },
]

export const INITIAL_STOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 'sm-1',
    itemId: 'inv-chicken-fillet',
    outletId: 'out-senopati',
    type: 'in',
    qty: 50,
    unitCostAtTime: 48000,
    balanceAfter: 50,
    reason: 'Penerimaan PO #0012 dari PT Agro Boga Utama',
    date: Date.now() - 3 * 86400000,
  },
  {
    id: 'sm-2',
    itemId: 'inv-chicken-fillet',
    outletId: 'out-senopati',
    type: 'out',
    qty: 12,
    unitCostAtTime: 48000,
    balanceAfter: 38,
    reason: 'Penjualan Dapur (Nasi Goreng & Ayam Bakar Kasir)',
    date: Date.now() - 1 * 86400000,
  },
  {
    id: 'sm-3',
    itemId: 'inv-beef-wagyu',
    outletId: 'out-senopati',
    type: 'in',
    qty: 30,
    unitCostAtTime: 110000,
    balanceAfter: 30,
    reason: 'Pengadaan Daging Wagyu Impor Supplier',
    date: Date.now() - 2 * 86400000,
  },
  {
    id: 'sm-4',
    itemId: 'inv-fresh-milk',
    outletId: 'out-senopati',
    type: 'in',
    qty: 70,
    unitCostAtTime: 19000,
    balanceAfter: 70,
    reason: 'Penerimaan Susu Diamond & Greenfields',
    date: Date.now() - 24 * 3600000,
  },
  {
    id: 'sm-5',
    itemId: 'inv-fresh-milk',
    outletId: 'out-senopati',
    type: 'out',
    qty: 18,
    unitCostAtTime: 19000,
    balanceAfter: 52,
    reason: 'Penjualan Minuman Bar (Auto Deduct POS)',
    date: Date.now() - 2 * 3600000,
  },
]

export const INITIAL_TABLES: TableFloor[] = [
  // SECTION INDOOR RESTO
  { id: 'tbl-1', outletId: 'out-senopati', name: 'Meja 01', section: 'Indoor', capacity: 2, status: 'available', shape: 'round' },
  { id: 'tbl-2', outletId: 'out-senopati', name: 'Meja 02', section: 'Indoor', capacity: 4, status: 'occupied', currentOrderId: 'ord-active-01', shape: 'square' },
  { id: 'tbl-3', outletId: 'out-senopati', name: 'Meja 03', section: 'Indoor', capacity: 4, status: 'available', shape: 'square' },
  { id: 'tbl-4', outletId: 'out-senopati', name: 'Meja 04', section: 'Indoor', capacity: 6, status: 'available', shape: 'rect' },

  // SECTION OUTDOOR TERAS
  { id: 'tbl-5', outletId: 'out-senopati', name: 'Outdoor 01', section: 'Outdoor', capacity: 4, status: 'available', shape: 'round' },
  { id: 'tbl-6', outletId: 'out-senopati', name: 'Outdoor 02', section: 'Outdoor', capacity: 4, status: 'occupied', currentOrderId: 'ord-active-02', shape: 'square' },
  { id: 'tbl-7', outletId: 'out-senopati', name: 'Outdoor 03', section: 'Outdoor', capacity: 6, status: 'billing', currentOrderId: 'ord-active-03', shape: 'rect' },

  // SECTION VIP ROOM
  { id: 'tbl-8', outletId: 'out-senopati', name: 'VIP Room 01', section: 'VIP', capacity: 8, status: 'available', shape: 'rect' },

  // SECTION BAR COUNTER
  { id: 'tbl-9', outletId: 'out-senopati', name: 'Bar 01', section: 'Bar', capacity: 2, status: 'available', shape: 'bar' },
  { id: 'tbl-10', outletId: 'out-senopati', name: 'Bar 02', section: 'Bar', capacity: 2, status: 'available', shape: 'bar' },

  // SECTION DAGO INDOOR (CABANG DAGO)
  { id: 'tbl-dg-1', outletId: 'out-dago', name: 'Meja 01', section: 'Indoor', capacity: 2, status: 'available', shape: 'round' },
  { id: 'tbl-dg-2', outletId: 'out-dago', name: 'Meja 02', section: 'Indoor', capacity: 4, status: 'occupied', currentOrderId: 'ord-dago-01', shape: 'square' },
  { id: 'tbl-dg-3', outletId: 'out-dago', name: 'Meja 03', section: 'Indoor', capacity: 4, status: 'available', shape: 'square' },
  { id: 'tbl-dg-4', outletId: 'out-dago', name: 'Meja 04', section: 'Indoor', capacity: 6, status: 'available', shape: 'rect' },

  // SECTION DAGO BALKON OUTDOOR (CABANG DAGO)
  { id: 'tbl-dg-5', outletId: 'out-dago', name: 'Balkon 01', section: 'Outdoor', capacity: 4, status: 'available', shape: 'round' },
  { id: 'tbl-dg-6', outletId: 'out-dago', name: 'Balkon 02', section: 'Outdoor', capacity: 4, status: 'available', shape: 'square' },
  { id: 'tbl-dg-7', outletId: 'out-dago', name: 'Bar 01', section: 'Bar', capacity: 2, status: 'available', shape: 'bar' },
]

export const INITIAL_SHIFT: Shift = {
  id: 'shift-today-01',
  outletId: 'out-senopati',
  staffId: 'usr-2',
  staffName: 'Kasir Utama',
  openingCash: 500000,
  systemExpectedCash: 500000 + 444213, // modal kas awal + total cash orders
  actualClosingCash: null,
  discrepancy: null,
  notes: 'Shift Pagi & Siang - Buka jam 09:00 WIB',
  openedAt: Date.now() - 7 * 3600000,
  closedAt: null,
}

export const INITIAL_ORDERS: Order[] = [
  // CABANG DAGO - ACTIVE ORDER DINE-IN (MEJA 02)
  {
    id: 'ord-dago-01',
    orgId: 'org-resto',
    outletId: 'out-dago',
    orderNumber: 'NBD-202610-0021',
    channel: 'dine_in',
    tableId: 'tbl-dg-2',
    tableName: 'Meja 02',
    customerName: 'Keluarga Dago (4 pax)',
    notes: 'Balkon luar sejuk, minta sambal dipisah',
    items: [
      {
        id: 'li-dg-1',
        menuItemId: 'menu-nasgor',
        name: 'Nasi Goreng Kampung Spesial',
        price: 38000,
        qty: 2,
        subtotal: 76000,
        notes: 'Pedas sedang',
        isKitchenItem: true,
        isCompletedInKitchen: false,
      },
      {
        id: 'li-dg-2',
        menuItemId: 'menu-latte',
        name: 'Iced Caffe Latte',
        price: 32000,
        qty: 2,
        subtotal: 64000,
        isKitchenItem: false,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 140000,
    discountAmount: 0,
    serviceChargeAmount: 7000,
    taxAmount: 14700,
    total: 161700,
    paymentMethod: 'qris',
    payments: [],
    status: 'preparing',
    staffId: 'usr-3',
    staffName: 'Kasir Dago',
    createdAt: Date.now() - 22 * 60000,
  },
  // CABANG DAGO - COMPLETED ORDER 1 (QRIS)
  {
    id: 'ord-dago-comp-01',
    orgId: 'org-resto',
    outletId: 'out-dago',
    orderNumber: 'NBD-202610-0019',
    channel: 'dine_in',
    tableId: 'tbl-dg-1',
    tableName: 'Meja 01',
    customerName: 'Ibu Ratna (Tamu Dago)',
    items: [
      {
        id: 'li-dg-c1',
        menuItemId: 'menu-sirloin',
        name: 'Sirloin Steak Meltique 200g',
        price: 95000,
        qty: 1,
        subtotal: 95000,
        isKitchenItem: true,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-dg-c2',
        menuItemId: 'menu-kopisusu',
        name: 'Kopi Susu Gula Aren Senja',
        price: 24000,
        qty: 1,
        subtotal: 24000,
        isKitchenItem: false,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 119000,
    discountAmount: 0,
    serviceChargeAmount: 5950,
    taxAmount: 12495,
    total: 137445,
    paymentMethod: 'qris',
    payments: [{ method: 'qris', amount: 137445 }],
    status: 'completed',
    staffId: 'usr-3',
    staffName: 'Kasir Dago',
    createdAt: Date.now() - 110 * 60000,
    completedAt: Date.now() - 65 * 60000,
  },
  // CABANG DAGO - COMPLETED ORDER 2 (CASH)
  {
    id: 'ord-dago-comp-02',
    orgId: 'org-resto',
    outletId: 'out-dago',
    orderNumber: 'NBD-202610-0020',
    channel: 'takeaway',
    customerName: 'Mas Dimas (Takeaway)',
    items: [
      {
        id: 'li-dg-c3',
        menuItemId: 'menu-burger',
        name: 'Wagyu Beef Burger & Truffle Fries',
        price: 65000,
        qty: 2,
        subtotal: 130000,
        isKitchenItem: true,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 130000,
    discountAmount: 0,
    serviceChargeAmount: 0,
    taxAmount: 13000,
    total: 143000,
    paymentMethod: 'cash',
    payments: [{ method: 'cash', amount: 143000 }],
    cashReceived: 150000,
    changeAmount: 7000,
    status: 'completed',
    staffId: 'usr-3',
    staffName: 'Kasir Dago',
    createdAt: Date.now() - 75 * 60000,
    completedAt: Date.now() - 55 * 60000,
  },
  // 1. ACTIVE ORDER DINE-IN (MEJA 02 SENOPATI)
  {
    id: 'ord-active-01',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0082',
    channel: 'dine_in',
    tableId: 'tbl-2',
    tableName: 'Meja 02',
    customerName: 'Tamu Meja 02 (4 pax)',
    notes: 'Dekat jendela, minta sambal dipisah',
    items: [
      {
        id: 'li-act-1',
        menuItemId: 'menu-nasgor',
        name: 'Nasi Goreng Kampung Spesial',
        price: 38000,
        qty: 2,
        subtotal: 76000,
        notes: 'Level Pedas: Sedang, Telur Ceplok 1 Matang 1 Setengah Matang',
        isKitchenItem: true,
        isCompletedInKitchen: false,
      },
      {
        id: 'li-act-2',
        menuItemId: 'menu-burger',
        name: 'Wagyu Beef Burger & Truffle Fries',
        price: 65000,
        qty: 1,
        subtotal: 65000,
        notes: 'Tingkat Kematangan: Medium Well',
        isKitchenItem: true,
        isCompletedInKitchen: false,
      },
      {
        id: 'li-act-3',
        menuItemId: 'menu-latte',
        name: 'Iced Caffe Latte',
        price: 32000,
        qty: 2,
        subtotal: 64000,
        notes: 'Less Sugar 50%, Gula Aren',
        isKitchenItem: false,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-act-4',
        menuItemId: 'menu-mocktail-sunset',
        name: 'Tropical Sunset Mocktail',
        price: 32000,
        qty: 1,
        subtotal: 32000,
        isKitchenItem: false,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 237000,
    discountAmount: 0,
    serviceChargeAmount: 11850,
    taxAmount: 24885,
    total: 273735,
    paymentMethod: 'qris',
    payments: [],
    status: 'preparing',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 18 * 60000,
  },

  // 2. ACTIVE ORDER DINE-IN (OUTDOOR 02 - ORDER BARU)
  {
    id: 'ord-active-02',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0083',
    channel: 'dine_in',
    tableId: 'tbl-6',
    tableName: 'Outdoor 02',
    customerName: 'Mbak Sarah (4 pax)',
    notes: 'Outdoor smoking area',
    items: [
      {
        id: 'li-act-5',
        menuItemId: 'menu-sirloin',
        name: 'Australian Sirloin Steak 200g',
        price: 115000,
        qty: 1,
        subtotal: 115000,
        notes: 'Medium, Saus Blackpepper, French Fries',
        isKitchenItem: true,
        isCompletedInKitchen: false,
      },
      {
        id: 'li-act-6',
        menuItemId: 'menu-carbonara',
        name: 'Spaghetti Carbonara Smoked Beef',
        price: 52000,
        qty: 1,
        subtotal: 52000,
        isKitchenItem: true,
        isCompletedInKitchen: false,
      },
      {
        id: 'li-act-7',
        menuItemId: 'menu-americano',
        name: 'Iced Americano',
        price: 25000,
        qty: 2,
        subtotal: 50000,
        notes: 'Less Ice, No Sugar',
        isKitchenItem: false,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-act-8',
        menuItemId: 'menu-matcha',
        name: 'Matcha Latte Oatmilk',
        price: 35000,
        qty: 1,
        subtotal: 35000,
        isKitchenItem: false,
        isCompletedInKitchen: false,
      },
    ],
    subtotal: 252000,
    discountAmount: 0,
    serviceChargeAmount: 12600,
    taxAmount: 26460,
    total: 291060,
    paymentMethod: 'cash',
    payments: [],
    status: 'preparing',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 11 * 60000,
  },

  // 3. ACTIVE ORDER DINE-IN (OUTDOOR 03 - BILLING / SIAP BAYAR)
  {
    id: 'ord-active-03',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0084',
    channel: 'dine_in',
    tableId: 'tbl-7',
    tableName: 'Outdoor 03',
    customerName: 'Komunitas Sepeda (6 pax)',
    notes: 'Minta split bill 6 orang saat bayar',
    items: [
      {
        id: 'li-act-9',
        menuItemId: 'menu-wings',
        name: 'Crispy Chicken Wings BBQ',
        price: 35000,
        qty: 3,
        subtotal: 105000,
        isKitchenItem: true,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-act-10',
        menuItemId: 'menu-fries',
        name: 'Truffle French Fries Parmesan',
        price: 28000,
        qty: 3,
        subtotal: 84000,
        isKitchenItem: true,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-act-11',
        menuItemId: 'menu-lychee-tea',
        name: 'Lychee Iced Tea',
        price: 28000,
        qty: 6,
        subtotal: 168000,
        isKitchenItem: false,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 357000,
    discountAmount: 0,
    serviceChargeAmount: 17850,
    taxAmount: 37485,
    total: 412335,
    paymentMethod: 'qris',
    payments: [],
    status: 'ready',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 34 * 60000,
  },

  // COMPLETED ORDERS HISTORIS (HARI INI)
  {
    id: 'ord-today-001',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0081',
    channel: 'dine_in',
    tableId: 'tbl-2',
    tableName: 'Meja 02',
    customerName: 'Bapak Hendra (Family)',
    items: [
      {
        id: 'li-1',
        menuItemId: 'menu-nasgor',
        name: 'Nasi Goreng Kampung Spesial',
        price: 38000,
        qty: 2,
        subtotal: 76000,
        notes: 'Level Pedas: Sedang, Telur Mata Sapi',
        isCompletedInKitchen: true,
      },
      {
        id: 'li-2',
        menuItemId: 'menu-burger',
        name: 'Wagyu Beef Burger & Truffle Fries',
        price: 65000,
        qty: 1,
        subtotal: 65000,
        notes: 'Daging Medium Well',
        isCompletedInKitchen: true,
      },
      {
        id: 'li-3',
        menuItemId: 'menu-latte',
        name: 'Iced Caffe Latte',
        price: 32000,
        qty: 2,
        subtotal: 64000,
        notes: 'Less Ice 50%',
        isCompletedInKitchen: true,
      },
      {
        id: 'li-4',
        menuItemId: 'menu-lychee-tea',
        name: 'Lychee Iced Tea',
        price: 28000,
        qty: 1,
        subtotal: 28000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 233000,
    discountAmount: 0,
    serviceChargeAmount: 11650,
    taxAmount: 24465,
    total: 269115,
    paymentMethod: 'qris',
    payments: [{ method: 'qris', amount: 269115 }],
    status: 'completed',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 32 * 60000,
    completedAt: Date.now() - 30 * 60000,
  },
  {
    id: 'ord-today-002',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0080',
    channel: 'dine_in',
    tableId: 'tbl-4',
    tableName: 'Meja 04',
    customerName: 'Ibu Ratna',
    items: [
      {
        id: 'li-5',
        menuItemId: 'menu-sirloin',
        name: 'Australian Sirloin Steak 200g',
        price: 115000,
        qty: 1,
        subtotal: 115000,
        notes: 'Tingkat Kematangan: Medium, Saus Mushroom',
        isCompletedInKitchen: true,
      },
      {
        id: 'li-6',
        menuItemId: 'menu-carbonara',
        name: 'Spaghetti Carbonara Smoked Beef',
        price: 52000,
        qty: 1,
        subtotal: 52000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-7',
        menuItemId: 'menu-mocktail-sunset',
        name: 'Tropical Sunset Mocktail',
        price: 32000,
        qty: 1,
        subtotal: 32000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-8',
        menuItemId: 'menu-americano',
        name: 'Iced Americano',
        price: 25000,
        qty: 1,
        subtotal: 25000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 224000,
    discountAmount: 22400,
    discountNote: 'Diskon Member VIP 10%',
    serviceChargeAmount: 10080,
    taxAmount: 21168,
    total: 232848,
    paymentMethod: 'cash',
    payments: [{ method: 'cash', amount: 232848 }],
    cashReceived: 250000,
    changeAmount: 17152,
    status: 'completed',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 75 * 60000,
    completedAt: Date.now() - 73 * 60000,
  },
  {
    id: 'ord-today-003',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0079',
    channel: 'bar',
    tableId: 'tbl-9',
    tableName: 'Bar 01',
    customerName: 'Pelanggan Walk-In',
    items: [
      {
        id: 'li-9',
        menuItemId: 'menu-latte',
        name: 'Iced Caffe Latte',
        price: 40000,
        qty: 1,
        subtotal: 40000,
        selectedModifiers: [{ id: 'opt-oat', name: 'Susu Oatly Barista', priceAdd: 8000 }],
        notes: 'Less Sugar 50%',
        isCompletedInKitchen: true,
      },
      {
        id: 'li-10',
        menuItemId: 'menu-croissant',
        name: 'Almond Butter Croissant',
        price: 26000,
        qty: 1,
        subtotal: 26000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 66000,
    discountAmount: 0,
    serviceChargeAmount: 3300,
    taxAmount: 6930,
    total: 76230,
    paymentMethod: 'qris',
    payments: [{ method: 'qris', amount: 76230 }],
    status: 'completed',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 110 * 60000,
    completedAt: Date.now() - 108 * 60000,
  },
  {
    id: 'ord-today-004',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0078',
    channel: 'dine_in',
    tableId: 'tbl-8',
    tableName: 'VIP Room 01',
    customerName: 'Keluarga Wijaya (Business Lunch)',
    items: [
      {
        id: 'li-11',
        menuItemId: 'menu-nasgor',
        name: 'Nasi Goreng Kampung Spesial',
        price: 38000,
        qty: 3,
        subtotal: 114000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-12',
        menuItemId: 'menu-sirloin',
        name: 'Australian Sirloin Steak 200g',
        price: 115000,
        qty: 2,
        subtotal: 230000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-13',
        menuItemId: 'menu-dori',
        name: 'Dori Crispy Sambal Dabu-Dabu',
        price: 42000,
        qty: 2,
        subtotal: 84000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-14',
        menuItemId: 'menu-fries',
        name: 'Truffle Parmesan French Fries',
        price: 28000,
        qty: 1,
        subtotal: 28000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-15',
        menuItemId: 'menu-wings',
        name: 'Crispy Chicken Wings BBQ',
        price: 35000,
        qty: 1,
        subtotal: 35000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-16',
        menuItemId: 'menu-latte',
        name: 'Iced Caffe Latte',
        price: 32000,
        qty: 4,
        subtotal: 128000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-17',
        menuItemId: 'menu-cheesecake',
        name: 'Lotus Biscoff Cheesecake',
        price: 38000,
        qty: 2,
        subtotal: 76000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 695000,
    discountAmount: 50000,
    discountNote: 'Voucher Promosi Rp 50.000',
    serviceChargeAmount: 32250,
    taxAmount: 67725,
    total: 744975,
    paymentMethod: 'transfer',
    payments: [{ method: 'transfer', amount: 744975 }],
    status: 'completed',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 175 * 60000,
    completedAt: Date.now() - 173 * 60000,
  },
  {
    id: 'ord-today-005',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0077',
    channel: 'bar',
    customerName: 'Gojek Online (#492)',
    items: [
      {
        id: 'li-18',
        menuItemId: 'menu-ayambakar',
        name: 'Ayam Bakar Sambal Matah',
        price: 45000,
        qty: 2,
        subtotal: 90000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-19',
        menuItemId: 'menu-tahu',
        name: 'Tahu Cabe Garam Crispy',
        price: 22000,
        qty: 1,
        subtotal: 22000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-20',
        menuItemId: 'menu-lychee-tea',
        name: 'Lychee Iced Tea',
        price: 28000,
        qty: 2,
        subtotal: 56000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 168000,
    discountAmount: 0,
    serviceChargeAmount: 0,
    taxAmount: 16800,
    total: 184800,
    paymentMethod: 'qris',
    payments: [{ method: 'qris', amount: 184800 }],
    status: 'completed',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 220 * 60000,
    completedAt: Date.now() - 218 * 60000,
  },
  {
    id: 'ord-today-006',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0076',
    channel: 'dine_in',
    tableId: 'tbl-6',
    tableName: 'Outdoor 02',
    customerName: 'Ananda P.',
    items: [
      {
        id: 'li-21',
        menuItemId: 'menu-burger',
        name: 'Wagyu Beef Burger & Truffle Fries',
        price: 65000,
        qty: 1,
        subtotal: 65000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-22',
        menuItemId: 'menu-matcha',
        name: 'Matcha Latte Premium',
        price: 35000,
        qty: 1,
        subtotal: 35000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 100000,
    discountAmount: 0,
    serviceChargeAmount: 5000,
    taxAmount: 10500,
    total: 115500,
    paymentMethod: 'cash',
    payments: [{ method: 'cash', amount: 115500 }],
    cashReceived: 120000,
    changeAmount: 4500,
    status: 'cancelled',
    notes: 'Dibatalkan oleh tamu: mendadak ada keperluan darurat (Voided)',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 280 * 60000,
    completedAt: Date.now() - 275 * 60000,
  },
  {
    id: 'ord-today-007',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0075',
    channel: 'dine_in',
    tableId: 'tbl-1',
    tableName: 'Meja 01',
    customerName: 'Clara & Rekan',
    items: [
      {
        id: 'li-23',
        menuItemId: 'menu-carbonara',
        name: 'Spaghetti Carbonara Smoked Beef',
        price: 52000,
        qty: 2,
        subtotal: 104000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-24',
        menuItemId: 'menu-americano',
        name: 'Iced Americano',
        price: 25000,
        qty: 2,
        subtotal: 50000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-25',
        menuItemId: 'menu-croissant',
        name: 'Almond Butter Croissant',
        price: 26000,
        qty: 1,
        subtotal: 26000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 180000,
    discountAmount: 0,
    serviceChargeAmount: 9000,
    taxAmount: 18900,
    total: 207900,
    paymentMethod: 'debit',
    payments: [{ method: 'debit', amount: 207900 }],
    status: 'completed',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 340 * 60000,
    completedAt: Date.now() - 338 * 60000,
  },
  {
    id: 'ord-today-008',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    orderNumber: 'NBR-202610-0074',
    channel: 'dine_in',
    tableId: 'tbl-3',
    tableName: 'Meja 03',
    customerName: 'Tamu Meja 03',
    items: [
      {
        id: 'li-26',
        menuItemId: 'menu-ayambakar',
        name: 'Ayam Bakar Sambal Matah',
        price: 45000,
        qty: 1,
        subtotal: 45000,
        isCompletedInKitchen: true,
      },
      {
        id: 'li-27',
        menuItemId: 'menu-caramel-macchiato',
        name: 'Caramel Macchiato',
        price: 38000,
        qty: 1,
        subtotal: 38000,
        isCompletedInKitchen: true,
      },
    ],
    subtotal: 83000,
    discountAmount: 0,
    serviceChargeAmount: 4150,
    taxAmount: 8715,
    total: 95865,
    paymentMethod: 'cash',
    payments: [{ method: 'cash', amount: 95865 }],
    cashReceived: 100000,
    changeAmount: 4135,
    status: 'completed',
    shiftId: 'shift-today-01',
    staffId: 'usr-4',
    staffName: 'Kasir Utama',
    createdAt: Date.now() - 390 * 60000,
    completedAt: Date.now() - 388 * 60000,
  },
]

export const INITIAL_FIXED_ASSETS: FixedAsset[] = [
  {
    id: 'fa-1',
    orgId: 'org-resto',
    code: 'AST-001',
    name: 'Kwali Range 2-Burner Heavy Duty & Blower Dapur',
    purchaseDate: Date.now() - 365 * 86400000,
    purchaseCost: 45000000,
    usefulLifeMonths: 48,
    residualValue: 5000000,
    accumulatedDepreciation: 10000000,
    monthlyDepreciation: 833333,
    coaAssetId: '1-1500',
    coaContraId: '1-1501',
    coaExpenseId: '6-4001',
  },
  {
    id: 'fa-2',
    orgId: 'org-resto',
    code: 'AST-002',
    name: 'Standing Chiller & Upright Freezer 4 Pintu Stainless',
    purchaseDate: Date.now() - 300 * 86400000,
    purchaseCost: 35000000,
    usefulLifeMonths: 48,
    residualValue: 5000000,
    accumulatedDepreciation: 6250000,
    monthlyDepreciation: 625000,
    coaAssetId: '1-1500',
    coaContraId: '1-1501',
    coaExpenseId: '6-4001',
  },
  {
    id: 'fa-3',
    orgId: 'org-resto',
    code: 'AST-003',
    name: 'Mesin Espresso Komersial 2-Group & Dual Grinder',
    purchaseDate: Date.now() - 250 * 86400000,
    purchaseCost: 85000000,
    usefulLifeMonths: 48,
    residualValue: 15000000,
    accumulatedDepreciation: 14583333,
    monthlyDepreciation: 1458333,
    coaAssetId: '1-1500',
    coaContraId: '1-1501',
    coaExpenseId: '6-4001',
  },
]

export const INITIAL_BILLS: PurchaseBill[] = [
  {
    id: 'bill-1',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    billNumber: 'BILL/202610/0001',
    vendorInvoiceNumber: 'INV-AGRO-4891',
    supplierId: 'sup-1',
    supplierName: 'PT Agro Boga Utama (Daging & Unggas)',
    date: Date.now() - 10 * 86400000,
    dueDate: Date.now() + 4 * 86400000,
    totalAmount: 4850000,
    paidAmount: 0,
    balanceDue: 4850000,
    status: 'unpaid',
  },
  {
    id: 'bill-2',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    billNumber: 'BILL/202610/0002',
    vendorInvoiceNumber: 'INV-SUKANDA-2219',
    supplierId: 'sup-2',
    supplierName: 'PT Sukanda Djaya (Dairy & Kentang)',
    date: Date.now() - 15 * 86400000,
    dueDate: Date.now() - 1 * 86400000, // Overdue
    totalAmount: 3200000,
    paidAmount: 1200000,
    balanceDue: 2000000,
    status: 'partial',
  },
]

export const INITIAL_SALES_INVOICES: SalesInvoiceB2B[] = [
  {
    id: 'inv-b2b-1',
    orgId: 'org-resto',
    outletId: 'out-senopati',
    invoiceNumber: 'INV/B2B/202610/0001',
    customerId: 'cust-1',
    customerName: 'PT Telkom Akses (Catering Meeting Direksi)',
    customerAddress: 'Gedung Menara Multimedia, Kebon Sirih, Jakarta',
    date: Date.now() - 5 * 86400000,
    dueDate: Date.now() + 9 * 86400000,
    items: [
      { itemId: 'menu-nasgor', name: 'Nasi Goreng Kampung Spesial Box', qty: 40, unit: 'porsi', unitPrice: 38000, subtotal: 1520000 },
      { itemId: 'menu-ayambakar', name: 'Ayam Bakar Sambal Matah Box', qty: 35, unit: 'porsi', unitPrice: 45000, subtotal: 1575000 },
      { itemId: 'menu-lychee-tea', name: 'Lychee Iced Tea Cup', qty: 75, unit: 'cup', unitPrice: 28000, subtotal: 2100000 },
    ],
    subtotal: 5195000,
    taxAmount: 519500, // PB1 Resto 10%
    totalAmount: 5714500,
    paidAmount: 2000000,
    balanceDue: 3714500,
    status: 'partial',
  },
]

export const INITIAL_WORK_ORDERS: WorkOrderProduction[] = []
export const INITIAL_TRANSFERS: StockTransfer[] = []

/**
 * SEED AKUNTANSI AWAL LENGKAP STANDAR ACCURATE & SAK EMKM
 */
export function seedInitialJournals(): JournalEntry[] {
  const journals: JournalEntry[] = []

  // 1. Jurnal Modal Awal Setoran Direksi
  journals.push({
    id: 'jnl-seed-modal',
    orgId: 'org-resto',
    journalNumber: 'JV/202610/0001',
    date: Date.now() - 30 * 86400000,
    refType: 'manual',
    description: 'Penyetoran Modal Awal Pendirian Resto & Cafe oleh Pemilik',
    lines: [
      { accountId: '1-1002', accountCode: '1-1002', accountName: 'Bank BCA Operasional', debit: 350000000, credit: 0 },
      { accountId: '3-1001', accountCode: '3-1001', accountName: 'Modal Disetor (Equity)', debit: 0, credit: 350000000 },
    ],
    totalAmount: 350000000,
    createdAt: Date.now() - 30 * 86400000,
  })

  // 2. Pembelian Aset Tetap Peralatan Dapur & Bar
  journals.push({
    id: 'jnl-seed-asset',
    orgId: 'org-resto',
    journalNumber: 'JV/202610/0002',
    date: Date.now() - 28 * 86400000,
    refType: 'manual',
    description: 'Pembelian Peralatan Dapur Komersial, Chiller, dan Mesin Bar',
    lines: [
      { accountId: '1-1500', accountCode: '1-1500', accountName: 'Peralatan Resto & Mesin Kopi', debit: 165000000, credit: 0 },
      { accountId: '1-1002', accountCode: '1-1002', accountName: 'Bank BCA Operasional', debit: 0, credit: 165000000 },
    ],
    totalAmount: 165000000,
    createdAt: Date.now() - 28 * 86400000,
  })

  // 3. Jurnal Pengadaan Bahan Baku (Hutang AP)
  INITIAL_BILLS.forEach((b, idx) => {
    journals.push({
      id: `jnl-seed-bill-${idx}`,
      orgId: 'org-resto',
      journalNumber: `JV/202610/${String(idx + 3).padStart(4, '0')}`,
      date: b.date,
      refType: 'purchase_bill',
      refId: b.id,
      description: `Faktur Pembelian ${b.billNumber} - ${b.supplierName}`,
      lines: [
        { accountId: '1-1201', accountCode: '1-1201', accountName: 'Persediaan Bahan Baku Makanan & Minuman', debit: b.totalAmount, credit: 0 },
        { accountId: '2-1001', accountCode: '2-1001', accountName: 'Hutang Usaha Supplier (AP)', debit: 0, credit: b.totalAmount },
      ],
      totalAmount: b.totalAmount,
      createdAt: b.date,
    })
  })

  // 4. Jurnal Piutang Catering B2B
  INITIAL_SALES_INVOICES.forEach((inv, idx) => {
    journals.push({
      id: `jnl-seed-inv-${idx}`,
      orgId: 'org-resto',
      journalNumber: `JV/202610/${String(idx + 5).padStart(4, '0')}`,
      date: inv.date,
      refType: 'sales_inv',
      refId: inv.id,
      description: `Faktur Penjualan B2B Catering ${inv.invoiceNumber} - ${inv.customerName}`,
      lines: [
        { accountId: '1-1101', accountCode: '1-1101', accountName: 'Piutang Usaha Pelanggan (AR)', debit: inv.totalAmount, credit: 0 },
        { accountId: '4-1001', accountCode: '4-1001', accountName: 'Pendapatan Penjualan Makanan & Minuman', debit: 0, credit: inv.subtotal },
        { accountId: '2-1100', accountCode: '2-1100', accountName: 'Hutang Pajak Restoran (PB1 10%)', debit: 0, credit: inv.taxAmount },
      ],
      totalAmount: inv.totalAmount,
      createdAt: inv.date,
    })
  })

  // 5. Jurnal Penjualan Kasir POS Harian
  INITIAL_ORDERS.filter((o) => o.status === 'completed').forEach((ord, idx) => {
    const cogsEst = Math.round(ord.subtotal * 0.28)
    const jnl = createJournalForPosSale(ord, cogsEst)
    jnl.id = `jnl-seed-pos-${idx}`
    jnl.journalNumber = `JV/202610/${String(idx + 10).padStart(4, '0')}`
    journals.push(jnl)
  })

  return journals
}
